// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/payment_controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "milestone3/be/internal/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentService is a mock of PaymentService interface.
type MockPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceMockRecorder
}

// MockPaymentServiceMockRecorder is the mock recorder for MockPaymentService.
type MockPaymentServiceMockRecorder struct {
	mock *MockPaymentService
}

// NewMockPaymentService creates a new mock instance.
func NewMockPaymentService(ctrl *gomock.Controller) *MockPaymentService {
	mock := &MockPaymentService{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentService) EXPECT() *MockPaymentServiceMockRecorder {
	return m.recorder
}

// CheckPaymentStatusMidtrans mocks base method.
func (m *MockPaymentService) CheckPaymentStatusMidtrans(orderId string) (dto.CheckPaymentStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPaymentStatusMidtrans", orderId)
	ret0, _ := ret[0].(dto.CheckPaymentStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPaymentStatusMidtrans indicates an expected call of CheckPaymentStatusMidtrans.
func (mr *MockPaymentServiceMockRecorder) CheckPaymentStatusMidtrans(orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPaymentStatusMidtrans", reflect.TypeOf((*MockPaymentService)(nil).CheckPaymentStatusMidtrans), orderId)
}

// CreatePayment mocks base method.
func (m *MockPaymentService) CreatePayment(req dto.PaymentRequest, userId, auctionItemId int) (dto.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", req, userId, auctionItemId)
	ret0, _ := ret[0].(dto.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentServiceMockRecorder) CreatePayment(req, userId, auctionItemId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentService)(nil).CreatePayment), req, userId, auctionItemId)
}

// GetAllPayment mocks base method.
func (m *MockPaymentService) GetAllPayment() ([]dto.PaymentInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPayment")
	ret0, _ := ret[0].([]dto.PaymentInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPayment indicates an expected call of GetAllPayment.
func (mr *MockPaymentServiceMockRecorder) GetAllPayment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPayment", reflect.TypeOf((*MockPaymentService)(nil).GetAllPayment))
}

// GetPaymentById mocks base method.
func (m *MockPaymentService) GetPaymentById(id int) (dto.PaymentInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentById", id)
	ret0, _ := ret[0].(dto.PaymentInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentById indicates an expected call of GetPaymentById.
func (mr *MockPaymentServiceMockRecorder) GetPaymentById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentById", reflect.TypeOf((*MockPaymentService)(nil).GetPaymentById), id)
}
