// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/bid_redis_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "milestone3/be/internal/repository"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockBidRedisRepository is a mock of BidRedisRepository interface.
type MockBidRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBidRedisRepositoryMockRecorder
}

// MockBidRedisRepositoryMockRecorder is the mock recorder for MockBidRedisRepository.
type MockBidRedisRepositoryMockRecorder struct {
	mock *MockBidRedisRepository
}

// NewMockBidRedisRepository creates a new mock instance.
func NewMockBidRedisRepository(ctrl *gomock.Controller) *MockBidRedisRepository {
	mock := &MockBidRedisRepository{ctrl: ctrl}
	mock.recorder = &MockBidRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBidRedisRepository) EXPECT() *MockBidRedisRepositoryMockRecorder {
	return m.recorder
}

// CheckDuplicateBid mocks base method.
func (m *MockBidRedisRepository) CheckDuplicateBid(userID, itemID int64, amount float64, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDuplicateBid", userID, itemID, amount, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckDuplicateBid indicates an expected call of CheckDuplicateBid.
func (mr *MockBidRedisRepositoryMockRecorder) CheckDuplicateBid(userID, itemID, amount, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDuplicateBid", reflect.TypeOf((*MockBidRedisRepository)(nil).CheckDuplicateBid), userID, itemID, amount, ttl)
}

// DeleteKey mocks base method.
func (m *MockBidRedisRepository) DeleteKey(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKey", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKey indicates an expected call of DeleteKey.
func (mr *MockBidRedisRepositoryMockRecorder) DeleteKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKey", reflect.TypeOf((*MockBidRedisRepository)(nil).DeleteKey), key)
}

// GetBidByKey mocks base method.
func (m *MockBidRedisRepository) GetBidByKey(key string) (repository.BidEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBidByKey", key)
	ret0, _ := ret[0].(repository.BidEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBidByKey indicates an expected call of GetBidByKey.
func (mr *MockBidRedisRepositoryMockRecorder) GetBidByKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBidByKey", reflect.TypeOf((*MockBidRedisRepository)(nil).GetBidByKey), key)
}

// GetEndTime mocks base method.
func (m *MockBidRedisRepository) GetEndTime(key string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEndTime", key)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEndTime indicates an expected call of GetEndTime.
func (mr *MockBidRedisRepositoryMockRecorder) GetEndTime(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEndTime", reflect.TypeOf((*MockBidRedisRepository)(nil).GetEndTime), key)
}

// GetHighestBid mocks base method.
func (m *MockBidRedisRepository) GetHighestBid(sessionID, itemID int64) (float64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighestBid", sessionID, itemID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHighestBid indicates an expected call of GetHighestBid.
func (mr *MockBidRedisRepositoryMockRecorder) GetHighestBid(sessionID, itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighestBid", reflect.TypeOf((*MockBidRedisRepository)(nil).GetHighestBid), sessionID, itemID)
}

// ScanKeys mocks base method.
func (m *MockBidRedisRepository) ScanKeys(pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanKeys", pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanKeys indicates an expected call of ScanKeys.
func (mr *MockBidRedisRepositoryMockRecorder) ScanKeys(pattern interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanKeys", reflect.TypeOf((*MockBidRedisRepository)(nil).ScanKeys), pattern)
}

// SetHighestBid mocks base method.
func (m *MockBidRedisRepository) SetHighestBid(sessionID, itemID int64, amount float64, userID int64, sessionEndTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHighestBid", sessionID, itemID, amount, userID, sessionEndTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHighestBid indicates an expected call of SetHighestBid.
func (mr *MockBidRedisRepositoryMockRecorder) SetHighestBid(sessionID, itemID, amount, userID, sessionEndTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHighestBid", reflect.TypeOf((*MockBidRedisRepository)(nil).SetHighestBid), sessionID, itemID, amount, userID, sessionEndTime)
}
