// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/bid_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "milestone3/be/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBidRepository is a mock of BidRepository interface.
type MockBidRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBidRepositoryMockRecorder
}

// MockBidRepositoryMockRecorder is the mock recorder for MockBidRepository.
type MockBidRepositoryMockRecorder struct {
	mock *MockBidRepository
}

// NewMockBidRepository creates a new mock instance.
func NewMockBidRepository(ctrl *gomock.Controller) *MockBidRepository {
	mock := &MockBidRepository{ctrl: ctrl}
	mock.recorder = &MockBidRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBidRepository) EXPECT() *MockBidRepositoryMockRecorder {
	return m.recorder
}

// SaveFinalBid mocks base method.
func (m *MockBidRepository) SaveFinalBid(bid *entity.Bid) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFinalBid", bid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFinalBid indicates an expected call of SaveFinalBid.
func (mr *MockBidRepositoryMockRecorder) SaveFinalBid(bid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFinalBid", reflect.TypeOf((*MockBidRepository)(nil).SaveFinalBid), bid)
}
